### ISSUE TITLE
Annotation Code available

### ISSUE THREAD

**Issue by nikky4D** [google/localized-narratives#1]
Hi, 

would you have the annotation codebase available? I would like to collect similar data for my work.

Thanks

**Comment by jponttuset** [comment]
Dear @nikky4D,

It is not in our immediate plans to release the annotation code, sorry.
If you have some specific technical questions about how to do it, though, I could help you.

Best,

**Comment by nikky4D** [comment]
Thanks. I'm working on annotating my own version for my particular use case, since the use of audio -to-text may actually make annotation more natural. As I progress, I will definitely ask questions. Thank you again.
