### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by shivangibithel** [google/localized-narratives#11]
Hi @jponttuset 

I am unable to download the raw voice recordings in the dataset. There is no such path, as mentioned in the documentation.

https://storage.googleapis.com/localized-narratives 
While accessing the above URL, I am getting the following error:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: localized-narratives/voice-recordings/</Details>
</Error>
```

**Comment by jponttuset** [comment]
Hi @shivangibithel,

If you check the documentation of the file format [here](https://google.github.io/localized-narratives/?file-formats=1), you'll see that you need to access the recordings by their direct URL, which is specified in the field `voice_recording` of the Localized Narrative.

For example, for `coco_val/coco_val_137576_93.ogg`, the URL is 
https://storage.googleapis.com/localized-narratives/voice-recordings/coco_val/coco_val_137576_93.ogg, which works properly.

**Comment by shivangibithel** [comment]
Hi, 

Thanks for the response. The url for Flickr dataset is not working.


https://storage.googleapis.com/localized-narratives/voice-recordings/flickr30k_val/flickr30k_val_219843859_180.ogg

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: localized-narratives/voice-recordings/flickr30k_val/flickr30k_val_219843859_180.ogg</Details>
</Error>
```

**Comment by jponttuset** [comment]
Hi @shivangibithel 
Thanks for your patience while I was debugging this issue.
I just realized that for Flickr30k, the image IDs are 0-padded to 16 characters, so in the case above it'd be:
https://storage.googleapis.com/localized-narratives/voice-recordings/flickr30k_val/flickr30k_val_0000000219843859_180.ogg

I'll fix the JSONL files ASAP, but in the meantime you can hack it as above.

**Comment by jponttuset** [comment]
Hi @shivangibithel,
The JSONL files on the website have been updated to point to the correct recording filename (it was wrong for Flickr30k and ADE20k). The rest of the file should be exactly the same.
Feel free to reopen this bug in case you still find some problems, and thank you very much for reporting the issue!

**Comment by shivangibithel** [comment]
Thank you for the quick response.
