### ISSUE TITLE
trace data

### ISSUE THREAD

**Issue by qizhust** [google/localized-narratives#2]
Hi, could you explain why the 'traces' is organized as List[List[TimePoint]] instead of List[TimePoint]?

**Comment by jponttuset** [comment]
Hi @qizhust,

The mouse trace sometimes gets out of the image+10% border and then gets in again. To represent this, each continuous trace segment is a List[TimePoint], thus all trace segments is a List[List[TimePoint]].

Does it make sense? If not I could draw a diagram.

**Comment by qizhust** [comment]
Thanks a lot! It's clear. @jponttuset
