### ISSUE TITLE
voice recording downloading

### ISSUE THREAD

**Issue by idejie** [google/localized-narratives#3]
Is there a collection or archive of all the voice recording ?

**Comment by jponttuset** [comment]
There is no archive, but you can download all voice recordings of a dataset using [gsutil](https://cloud.google.com/storage/docs/gsutil). For example:
```
gsutil -m cp -r gs://localized-narratives/voice-recordings/coco_val .
```
Will download all recordings of COCO validation.

The `-m` option downloads files in parallel, so it should be pretty quick.

**Comment by idejie** [comment]
thank you!
