### ISSUE TITLE
Controlled Captioning Baseline

### ISSUE THREAD

**Issue by naykun** [google/localized-narratives#4]
Hi, thank you for your impressive work!
I'm currently building my captioning model on this dataset. And I'm wondering whether can you provide your Controlled Image Captioning baseline code? I believe that will lead to more fair comparable works on this topic and will boost the influence of this dataset.

**Comment by jponttuset** [comment]
Hi @naykun, thanks for your kind words.

We are working on releasing the code and models for our controlled captioning experiments.
I'll reply to this issue as soon as we make it available.

Best,

**Comment by jponttuset** [comment]
In the end we didn't release the baseline. Apologies.
