### ISSUE TITLE
Question about controlled caption evaluation

### ISSUE THREAD

**Issue by naykun** [google/localized-narratives#5]
Hi, I have a question about the evaluation process. 
Since in the validation set, an image may have multiple traces according to your annotation. Which trace is taken as input? If we take each trace as an individual item to evaluate, we will get multiple hypotheses for a single image id, which is inconsistent with the default setting in the MS coco caption evaluation tool.
A more detailed explanation on how to reproduce the reported results is a great help. 
Many thanks for considering my request.

**Comment by jponttuset** [comment]
Dear @naykun,

We always evaluate against one single caption, the one that was produced together with the trace that we use as input. If an image has various Localized Narratives, then we evaluate twice on that image, but always against 1 caption.

Does this clarify your doubts?

**Comment by naykun** [comment]
Yeah, that's clear enough! To be frank, the trace concatenated baseline you provided is a very strong one! Haaah
Well, thanks for your reply!

**Comment by jponttuset** [comment]
Hi @naykun, thanks for your kind words about our work.
Good luck with your research!
