### ISSUE TITLE
Data download link broken

### ISSUE THREAD

**Issue by hackgoofer** [google/localized-narratives#6]
https://google.github.io/localized-narratives/

The download for all datasets are broken. 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

**Comment by jponttuset** [comment]
Hi @ytsheng,

Thanks for reporting and sorry for the inconvenience.
We are aware of the problem and we're working hard to fix it ASAP.

Best,

**Comment by jponttuset** [comment]
Hi again,

The data is now available again. Sorry for the inconvenience.

Closing the issue, but if you find some links not working yet, feel free to reopen.
