### ISSUE TITLE
Are x and y coordinates given with the upper left corner as origin?

### ISSUE THREAD

**Issue by rubencart** [google/localized-narratives#7]
Like title says, where is the origin of the x and y coordinate system in the traces in the .jsonl files? I could not find this on your website or in your paper. Maybe I didn't look carefully? Else, I think it would make sense to mention it somewhere.

**Comment by jponttuset** [comment]
Hi @rubencart 

Thanks for pointing this out. The origin is indeed the upper left corner of the image.
I have now specified this in the website, under "[Format description](https://google.github.io/localized-narratives/?file-formats=1)".

Best,
